### ISSUE TITLE
One Clink deploy to Heroku

### ISSUE THREAD

**Issue by ohld** [adw0rd/instagrapi-rest#1]
It would be awesome (and might scalable) if the project would have "one-click deploy to Heroku" button. This will allow to use free and always on Heroku instance while spending time on the code and logic only.

Here you can find example buttons and heroku configs (with .env vars setup during onbording).

https://github.com/ohld/telegram-support-bot/blob/main/app.json

**Comment by adw0rd** [comment]
@ohld button added
