### ISSUE TITLE
Idea: change the API so that it remembers the session id, we don't have to provide it each time

### ISSUE THREAD

**Issue by Soneji** [adw0rd/instagrapi-rest#10]
Hi

I am trying to make an app using this incredible tool, however I feel some of the logic could be streamlined if the internal state of the REST API allowed for saving the session id, or at least having a mode for this. I would like to be able to:

- login (once)
- send request to make an instagram post with just the account username (can be many times across many days)
  - if there is an existing session, use that token to make the post
  - if there is not an existing session, return error
    - user can handle the error by sending the login request again, and then the instagram post request

The benefit of something like this is that I don't have to worry about storing any session id, which could change/become invalid at any time, within my application. I just need to store my IG user/pass, which can be used if and when the session id becomes invalid.

I feel like this could be quite easily achieved using the library "load_settings" and "dump_settings" and stored in a particular location, such as `/etc/instagrapi-rest/user1.json, user2.json...`

Then for Docker users (like myself), we can map that folder to a volume, ensuring that the state is maintained across container restarts. This also provides the benefit that the "device" info is maintained across container restarts too, so "Instagram can trust you more".

**Comment by adw0rd** [comment]
We already store the session (https://github.com/adw0rd/instagrapi-rest/blob/main/storages.py#L6), but it is assumed that this api is used for multiple accounts, in order to have access to several accounts at once, their identifier must be transmitted (now this is the sessionid, since it is most convenient to work with it)

**Comment by adw0rd** [comment]
> The benefit of something like this is that I don't have to worry about storing any session id, which could change/become invalid at any time, within my application. I just need to store my IG user/pass, which can be used if and when the session id becomes invalid.
> 
> I feel like this could be quite easily achieved using the library "load_settings" and "dump_settings" and stored in a particular location, such as /etc/instagrapi-rest/user1.json, user2.json...

You do not need to do load/dump, everything is already provided inside this service

**Comment by adw0rd** [comment]
> Then for Docker users (like myself), we can map that folder to a volume, ensuring that the state is maintained across container restarts. This also provides the benefit that the "device" info is maintained across container restarts too, so "Instagram can trust you more".

Yes, I agree, sessions are now stored in memory. After restarting the container, you will lose them and you will need to log in again. When saving to a store, I suggest doing a dump into a shared volume and reading it at startup (load_settings). Can you do it?

**Comment by Soneji** [comment]
Yeah I have been playing around with this just today, and I just concluded they are stored in memory. I can try make a PR for this to update storages.py to use a file instead of in memory, is that what you think is best?

**Comment by adw0rd** [comment]
@Soneji yes, thanks!

**Comment by Soneji** [comment]
fab stuff, thanks :)
