### ISSUE TITLE
[BUG] Raspberry Pi/Arm support

### ISSUE THREAD

**Issue by Soneji** [adw0rd/instagrapi-rest#11]
I would like to run this API on my pi, but have been unable to do so because the image this API is based on, only runs on x86. 

I have managed to get it running on my pi by modifying the Dockerfile a little and copying a few (around 5) files from the https://github.com/tiangolo/uvicorn-gunicorn-docker project. 

This would also reduce the project's dependance on external Docker images. Dependance could be bad if the owners disappear.

If this is something you'd be willing to support, let me know and I can make a PR. 

```diff

diff --git a/Dockerfile b/Dockerfile
index 3f0cad6..1231591 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,34 @@
-FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim
+# gunicorn image
+FROM python:3.8-slim as my_gunicorn

+RUN apt-get update \
+&& apt-get install gcc ffmpeg -y \
+&& apt-get clean
+
+RUN pip install --no-cache-dir "uvicorn[standard]" gunicorn
+
+COPY uvicorn-gunicorn-docker/docker-images/start.sh /start.sh
+RUN chmod +x /start.sh
+
+COPY uvicorn-gunicorn-docker/docker-images/gunicorn_conf.py /gunicorn_conf.py
+
+COPY uvicorn-gunicorn-docker/docker-images/start-reload.sh /start-reload.sh
+RUN chmod +x /start-reload.sh
+
+COPY uvicorn-gunicorn-docker/docker-images/app /app
+WORKDIR /app/
+
+ENV PYTHONPATH=/app
+
+EXPOSE 80
+
+# Run the start script, it will check for an /app/prestart.sh script (e.g. for migrations)
+# And then will start Gunicorn with Uvicorn
+CMD ["uvicorn-gunicorn-docker/docker-images/start.sh"]
+
+
+#FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim
+FROM my_gunicorn
 # RUN apt-get update \
 #     && apt-get install --yes --no-install-recommends \
 #         build-essential python-dev
@@ -13,4 +42,5 @@ COPY . /app/
 WORKDIR /app
 RUN pip install -r requirements.txt

-CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
\ No newline at end of file
+CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
+
```

**Comment by adw0rd** [comment]
@Sonejiit working on Apple Air M1 (arm), not only x86.

![image](https://user-images.githubusercontent.com/546889/132859362-4a514737-ed1f-453a-9672-83806a2cfc34.png)

But I will be glad if it works for rpi, send your PR

**Comment by Soneji** [comment]
I am running it also on my m1 macbook air with no problem, but if you open docker desktop it shows like this

![image](https://user-images.githubusercontent.com/12625848/132925403-893a21e7-8db9-42d2-9bbf-de777578ce33.png)

just wondering if yours is also running in docker's compatibility mode

**Comment by adw0rd** [comment]
@Soneji yes

![image](https://user-images.githubusercontent.com/546889/132963723-f4334dc7-f7a3-4e04-aa6f-f124cea7ba0a.png)

**Comment by Soneji** [comment]
haha, thought so! ;p
