### ISSUE TITLE
/media/pk_from_url not working

### ISSUE THREAD

**Issue by Soneji** [adw0rd/instagrapi-rest#15]
Python console
```py
>>> Client().media_pk_from_url("https://www.instagram.com/p/CTZRfJEDsE7/")
2655230362137837883
```

API request: 
![image](https://user-images.githubusercontent.com/12625848/133164070-1ec22068-3ab6-4932-8639-9db1aa79e1f9.png)

API logs:

```
api_1  | https://www.instagram.com/p/CTZRfJEDsE7/
api_1  | INFO:     172.28.0.1:39612 - "GET /media/pk_from_url?url=https%3A%2F%2Fwww.instagram.com%2Fp%2FCTZRfJEDsE7%2F HTTP/1.1" 200 OK
```

I added in a print to see the URL is correct... not sure why it's not working, and appears to be adding extra zeroes
![image](https://user-images.githubusercontent.com/12625848/133164138-fc96744c-6e57-4146-add4-3274e3d3d520.png)

**Comment by adw0rd** [comment]
Why do you think it doesn't work? Your screenshot has the correct answer:

![image](https://user-images.githubusercontent.com/546889/133167047-62c21ef6-2f87-42b7-8ad5-939e3fe9bbbe.png)

**Comment by Soneji** [comment]
I don't get it?

**Comment by adw0rd** [comment]
> I don't get it?

Describe your question in more detail

**Comment by Soneji** [comment]
| Service | response |
|-|-|
| Python gives | 2655230362137837883 |
| API gives      | 2655230362137838000 |
API is giving wrong data...?

**Comment by adw0rd** [comment]
@Soneji now I see the problem, thanks!
