### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alexdumitru89** [adw0rd/instagrapi-rest#22]
### Compensate with donations ($5 and more) for the time I spent to fix problems or send  me your [Pull Request](https://github.com/adw0rd/instagrapi-rest/pulls) with fixes

* Bitcoin: 3KHgnvNNWio6wyQ71cgNeBQojXStxzkzfd
* Ethereum: 0x6e644c6b975B47801072b07a9a57DDfEC10DE74F
* https://paypal.me/adw0rd
* https://www.patreon.com/adw0rd
* https://www.buymeacoffee.com/adw0rd
* For Russia: СБП, Qiwi и тп: **+79118107609**

**Describe the bug**

I ran the docker image and I only see 2 options in the API

![image](https://user-images.githubusercontent.com/5942561/134328153-16eec0ef-4aa6-4249-a2ad-d1b32395e756.png)

**To Reproduce**

I ran the docker image by `docker run -p 8000:8000 adw0rd/instagrapi-rest`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by adw0rd** [comment]
Updated https://hub.docker.com/repository/docker/adw0rd/instagrapi-rest
