### ISSUE TITLE
Session not found (e.g. after reload process), please relogin

### ISSUE THREAD

**Issue by iaminnasr** [adw0rd/instagrapi-rest#49]
Hi
When I want to enter the session without login in relogin, I get it 
     {
  "detail": "Session not found (e.g. after reload process), please relogin",
  "exc_type": "Exception"
}

**Comment by adw0rd** [comment]
So you need to relogin

**Comment by iaminnasr** [comment]
i get this error when relogin api 
curl -X 'POST' \
  'http://localhost:8001/auth/relogin' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'sessionid=ssss'


{
  "detail": "Session not found (e.g. after reload process), please relogin",
  "exc_type": "Exception"
}

**Comment by iaminnasr** [comment]
I already have a session in my db, I don't want to login 
i just set seession in api without call login api

**Comment by adw0rd** [comment]
Fix it then and send a PR
