### ISSUE TITLE
Adding features

### ISSUE THREAD

**Issue by huyparody** [adw0rd/instagrapi-rest#7]
I suggest that you should add more features like
- The "Insight" feature from the instagrapi
- The friendship status of user with list user following (isBestie, isFollowingYou, v.v)
- The rest api to know if someone unfollow user himself?

**Comment by adw0rd** [comment]
I added insights support and so I close this issue

**Comment by huyparody** [comment]
> I added insights support and so I close this issue

Great! Thanks

**Comment by adw0rd** [comment]
@huyparody create different tasks, no need to put an unrelated list of tasks in one
